version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${SPRING_DATASOURCE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: ${DOCKER_USERNAME}/my-web-image
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_HOST=${SPRING_DATASOURCE_HOST}
      - SPRING_DATASOURCE_PORT=${SPRING_DATASOURCE_PORT}
      - SPRING_DATASOURCE_NAME=${SPRING_DATASOURCE_NAME}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - RESTAPI_KAKAO=${RESTAPI_KAKAO}
      - KAKAO_REDIRECT=${KAKAO_REDIRECT}
      - FIREBASE_AUTH_API=${FIREBASE_AUTH_API}
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      # 볼륨 경로를 /home/ubuntu 에 생성된 파일로 변경
      - ./application.yml:/src/main/resources/application.yml:ro
      - ./effort-stone-firebase-admin.json:/src/main/resources/effort-stone-firebase-admin.json:ro

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    env_file:
      - .env
    ports:
      - "8081:8080"
    depends_on:
      - app

volumes:
  postgres-data:
