## version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${SPRING_DATASOURCE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_HOST=${SPRING_DATASOURCE_HOST}
      - SPRING_DATASOURCE_PORT=${SPRING_DATASOURCE_PORT}
      - SPRING_DATASOURCE_NAME=${SPRING_DATASOURCE_NAME}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - RESTAPI_KAKAO=${RESTAPI_KAKAO}
      - KAKAO_REDIRECT=${KAKAO_REDIRECT}
      - FIREBASE_AUTH_API=${FIREBASE_AUTH_API}
    ports:
      - "8080:8080"

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    environment:
      -  URLS_PRIMARY_NAME=my-api
      - "URLS=[{ url: 'http://localhost:8080/v3/api-docs', name: 'My API' }]"
      -  SUPPORTED_SUBMIT_METHODS=['get', 'post', 'put', 'delete']
    ports:
      - "8081:8080"
    depends_on:
      - app

volumes:
  postgres-data:


