name: Deploy to EC2

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Create configuration files from secrets
      - name: Create Docker Compose (production)
        if: github.ref == 'refs/heads/main'
        run: printf '%s' "${{ secrets.DOCKER_COMPOSE_PROD }}" > docker-compose.prod.yml

      - name: Create Docker Compose (test)
        if: github.ref == 'refs/heads/develop'
        run: printf '%s' "${{ secrets.DOCKER_COMPOSE_TEST }}" > docker-compose.test.yml

      - name: Create application.yml
        run: printf '%s' "${{ secrets.APPLICATION_YML }}" > application.yml

      - name: Create firebase-admin.json
        run: printf '%s' "${{ secrets.FIREBASE_ADMIN_JSON }}" > firebase-admin.json

      - name: Create environment variables file (.env)
        run: printf '%s' "${{ secrets.ENV_VARS }}" > .env

      # Deploy to appropriate server based on branch
      - name: Ensure target directory (production)
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu               # adjust if your EC2 user is different (e.g., ec2-user)
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: mkdir -p ~/app

      - name: Ensure target directory (test)
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: mkdir -p ~/app

      - name: Copy files to server (production)
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "./docker-compose.prod.yml,./application.yml,./firebase-admin.json,./.env,./nginx.conf"
          target: "~/app/"

      - name: Copy files to server (test)
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "./docker-compose.test.yml,./application.yml,./firebase-admin.json,./.env,./nginx.conf"
          target: "~/app/"

      - name: Deploy application (production)
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/app
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml up -d

      - name: Deploy application (test)
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/app
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
            docker-compose -f docker-compose.test.yml pull
            docker-compose -f docker-compose.test.yml up -d
